### PR TITLE
Add Lyft Apprenticeship

### PR DESCRIPTION
**Pull request by VelazquezAJ**
Applications for Lyft's apprenticeship program are up.

---

## ✅️ By submitting this PR, I have verified the following

- [X] Checked to see if a similar PR has already been opened 🤔️
- [X] Reviewed the contributing guidelines 🔍️
- [ ] Added my name to the bottom of the list under the **Credits** section in the `README.md` with a link to my website or GitHub profile 👥️ (Do you still want me to do this? I feel weird since I'm just adding our posting)

### CODE REVIEW

**Comment by VelazquezAJ** [comment]
Ah, I think I was working off an old version too. I've got the image included and removed the draft property~

**Comment by fvcproductions** [comment]
@VelazquezAJ just one last thing, we require images to be a certain width/height - see contributing docs 📝

**Comment by VelazquezAJ** [comment]
I promise I know how to read despite current evidence! :X

Updated the image to be 1000px x 500px

**Comment by fvcproductions** [comment]
@benjaminmodayil can I get your insight here on why deploy preview doesn't work for this PR? Do you think it's just because @VelazquezAJ needs to rebase? Just double checking.

**Comment by benjaminmodayil** [comment]
Ah. So this was something I had a part of and may have not communicated...
Sorry! While I was exploring how we would handle the image fix, to make it
easier to parse from the frontmatter I had set it up where you no longer
need to specify the path to the image. As long it is in the images folder
all you have to specify is lyft.jpg instead of
images/apprenticeships/Lyft.jpg


Sorry for not communicating this. I can either provide a fix for the old
path or we could set it up to just the filename. Whatever works for you
Frances.

Sorry Anthony!

**Comment by fvcproductions** [comment]
@benjaminmodayil it can be just the filename for now but ideally we have a fix for this in the future when we migrate to just using Hugo & Gulp since this doesn't scale well if we want to add more pages in 😬

totally fine for now though - i can make the quick fix myself!

**Pull request merged**
