### PR TITLE
Added LaunchPad Lab to Apprenticeships

### PR DESCRIPTION
**Pull request by bgongre**
Insert description of PR here

Added the LaunchPad Lab apprenticeship as requested by the company. (#164)

**update**

Added Quora to list of apprenticeships. (#172 #173)

---

## ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Added my name to the bottom of the list under the **Credits** section in the `README.md` with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by bgongre** [comment]
I pulled the repo to check out the Quora image. It has been resized to 1000px by 500px based on the image that was provided in the request. The LaunchPad Lab didn't have an image included, I was able to make that one myself using their company logo and color. I can try to resize the Quora logo smaller if that is what it the issue is?

**Comment by fvcproductions** [comment]
@bgongre Okay we can move forward for now then with those images after the package-lock.json conflicts are resolved 👍🏽

**Comment by bgongre** [comment]
Ran an 'npm audit fix' on npm dependencies and updated everything. From what I can tell from looking at the conflicts, the master (apprenticeships.me) is showing the old versions of some dependencies and I'm trying to push the updated versions. Please let me know if this is incorrect.

**Comment by fvcproductions** [comment]
@bgongre Yes apologies for not being as clear, if you could revert both those package files to the version on master, then I can move forward with merging.

**Pull request merged**
