### PR TITLE
Create genm.md for apprenticeships

### PR DESCRIPTION
**Pull request by mdb1710**
Insert description of PR here

---

## ✅️ By submitting this PR, I have verified the following

- [] Checked to see if a similar PR has already been opened 🤔️
- [] Reviewed the contributing guidelines 🔍️
- [] Added my name to the bottom of the list under the **Credits** section in the `README.md` with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
@mdb1710 you must add the image yourself

**Comment by mdb1710** [comment]
@fvcproductions I've just uploaded the image directly to the folder for the pull request.

**Comment by fvcproductions** [comment]
@benjaminmodayil do you know why netlify preview isn't working? 🤔

**Comment by benjaminmodayil** [comment]
@fvcproductions  I'm not 100% sure, but I do know there is a bug created by me that might be blocking it (sorry!). In my last PR I tried to throw errors whenever the image script broke to catch Netlify from deploying a broken build... Now I think it doesn't deploy.

I'll be opening a PR tonight that fixes this issue by:
1. Removing my hacky image path script that was needed for a time because of Parcel's image hashing Algolia's indexing.
2. Removing Parcel as it enforces image hashing and will force us to do workarounds to get Algolia to work.

We should also never need to redeploy the site if the images get broken from bot PRs and others creating pull requests. 

It looks good right now locally, but just want to be sure.

**Comment by fvcproductions** [comment]
Let's add this in now

**Pull request merged**
