### PR TITLE
fix broken builds + image issues

### PR DESCRIPTION
**Pull request by benjaminmodayil**
This PR will fix future problems with broken images whenever a new deployment occurs. It will also unblock Netlify builds from creating preview links.

### CODE REVIEW

**Comment by benjaminmodayil** [comment]
The file the ABC bot is having issues with is generated from the postcsscli, not sure what to do about that one.

**Comment by benjaminmodayil** [comment]
Eventually this generated file from the postcss file will cease to exist, but is required now until I can figure out the best for Hugo to reference a postcss file and recognize it's the dev css file.

**Comment by fvcproductions** [comment]
Fixed the merge conflict since I merged another PR with an update to the `package-lock.json`

**Comment by benjaminmodayil** [comment]
@fvcproductions  Anything blocking this PR that I should fix?

**Comment by fvcproductions** [comment]
@benjaminmodayil No we can merge, sorry for delay!

**Pull request merged**
