### PR TITLE
Form submits issue to Repository via lambda function

### PR DESCRIPTION
**Pull request by benjaminmodayil**
When submitting the form, the client-side JS submits a post request to `/.netlify/functions/form` and that submits a post request to the repository. Why a lambda function? Because I needed to hide the access token.

There is an error state as well as a success state. I recommend running it locally to test the error state as it won't work locally 😅. 

Sorry for all the notifications for issues... Also sorry for all the commits on this branch. I couldn't figure a good way to test it without deploying the preview.

Also sorry for this being added so late. I'll let you decide whether to merge this before launch.

At the moment, it appears issues will be added via my name. I'm a little scared that this will be abused somehow with spam being fed directly to our issues.

### CODE REVIEW

**Comment by benjaminmodayil** [comment]
@fvcproductions Not sure how to solve that one code factor issue since the line that needs to render is pretty long.

**Comment by fvcproductions** [comment]
I think we can still get this added in before PH Launch because I wasn't able to commit to 4/15 launch anyways - been too busy with work 😹 - we can push date until this is completed and the mobile view looks a bit better for the site in general

Also I would let users know that by submitting the form, they will automatically create an issue. In fact, I wonder if we can display the issue link after submission? 🤔

**Comment by benjaminmodayil** [comment]
I'll work on addressing these tonight. Thanks for the feedback!

**Comment by benjaminmodayil** [comment]
@fvcproductions Should the imageURL be required? The image URLs in the markdown refer to an image also found in the project folder

Part of me feels like it could be easier for people to add the image to the repository at that point versus finding an online hosted logo image that they could link in the form. I'm just thinking about who might use the form (less technical folk) versus the repository (more technical folk). Also a part of me feels like whoever handles the issue in the end could find the image and incorporate that in our repo instead.

Idk. Let me know how you'd like me to proceed with that.

**Comment by fvcproductions** [comment]
@benjaminmodayil good point! we can leave out the image input for now so there's less of a barrier

**Comment by fvcproductions** [comment]
This pull request **introduces 1 alert** when merging 16f16a68bc94726db09ea81e38074b43dd4ab398 into 52474914fe311a1c5dc7e56dc7109586b6e40d23 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-ab1039876dc674eb6947759a30b327e16c758450)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
This pull request **introduces 1 alert** when merging a01de867563effd2c10a16e52f064a0bb379f064 into 52474914fe311a1c5dc7e56dc7109586b6e40d23 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-5b789ca56ba6163e324e3db5f3be33c9a125f349)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
This pull request **introduces 1 alert** when merging 3192995b6e4be746d445697792b16ca66ff5ee9d into 52474914fe311a1c5dc7e56dc7109586b6e40d23 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-e8b3e8e96fb6959fa1d69fb8d2904ddafe5219e8)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
This pull request **introduces 1 alert** when merging 8dd089924c4821f200358fad6daf21971e1bbebf into 52474914fe311a1c5dc7e56dc7109586b6e40d23 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-f067df8cb0aa4298455f3b71f5106128a8379854)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
This pull request **introduces 2 alerts** when merging 235e4574d2df82e6c1786daaed28017a3be7731c into 52474914fe311a1c5dc7e56dc7109586b6e40d23 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-ffe60e43c522ebde39810b5903a8216038e69281)

**new alerts:**

* 2 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by benjaminmodayil** [comment]
@fvcproductions Sorry if this PR is holding us back from launching. My company is having two all-hands-on-deck meetings so I'll be in the office Wednesday (today) + Thursday until 7:30pm + 1hr of travel (8:30pm) so I'm having a hard time at the moment to find time to work on this one. I'll try to wrap this up tonight. One of the huge difficulties is that I can only test the lambda form component when it's actually pushed to the repository + netlify as it doesn't work properly locally without a painful setup with proxies. Do we have a new date that we are trying to launch on that I can work towards?

**Comment by fvcproductions** [comment]
@benjaminmodayil No pressure - we are okay to launch what you feel more comfortable with. There's no real rush!

Let's change the date to launch on April 29th - does that work for you?

**Comment by benjaminmodayil** [comment]
That day sounds great for me! Thanks!

**Comment by fvcproductions** [comment]
@benjaminmodayil Feel free to ping me when this is ready for another review FYI 💯

**Comment by benjaminmodayil** [comment]
@fvcproductions Done! Sorry for it coming to the last minute. I've been busy as of late.

**Comment by fvcproductions** [comment]
@benjaminmodayil apologies for all the github bots - i've been experimenting with them and i can tell which ones aren't worth keeping now 😂

**Comment by benjaminmodayil** [comment]
@fvcproductions Haha I was about to ask about the bots... The restyled-bot seems to be generating extra Netlify previews on every commit as well.

Let me know if anything else needs to change!

**Comment by fvcproductions** [comment]
@benjaminmodayil I get the following when I try looking at the page:

Screen Shot 2019-04-29 at 1 18 54 PM


I also think we should just have `https://` as placeholder for URL

Otherwise, I think it looks fine and we can share on PH next Monday instead so it's on a Monday (Monday launches gain more traction, right?) 🤷🏽‍♀️ - what do you think?

**Comment by benjaminmodayil** [comment]
@fvcproductions Sorry, I should have mentioned the following earlier. View the branch preview link over the deploy preview link: http://netlify-form--apprenticeships.netlify.com

I have to register each domain name with the recaptcha settings on Google so this was an easier method versus adding each deploy preview URL since those are created on commit.

Whatever date works best for you! Sounds good with me.

**Comment by fvcproductions** [comment]
Oh my bad - that looks then @benjaminmodayil!

**Pull request merged**
