### PR TITLE
re-added image templating + create image path script

### PR DESCRIPTION
**Pull request by benjaminmodayil**
This PR fixes the image paths for the displayed images when Algolia search loads.

To solve #83, I tried initially getting rid of the hashes generated by Parcel in the `dist` folder but Parcel does not allow this. I also thought about the possibility of removing Parcel in general, but our process with Babel relies on this and it would require a bigger lift to remove without possibly breaking something.

Instead, I created a small script that runs in our build step that looks for the `public/algolia.json` file and looks at the `dist` directory to find the images with hashes and add those into our JSON file. It feels hacky to be honest, but might be what we need to meet our Product Hunt deadline if we still launch the 15th.

### CODE REVIEW

**Comment by benjaminmodayil** [comment]
IT WORKS. So glad this bug is gone. Let me know what you think about the solution. I wasn't sure how to fix it otherwise. I'll address the Code Factor bot issues + refactoring some of this in the morning.

**Comment by fvcproductions** [comment]
This pull request **introduces 2 alerts** when merging 085fe6edf36224472dec19eff48e3bf163e46ebf into 385064f1fa9626145d16a019324e4eca99f0e089 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-7b4d913b8e0d0f32fb202585d21e23e8bf5887b9)

**new alerts:**

* 1 for Missing variable declaration
* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
This pull request **introduces 1 alert** when merging b47de2dc11211bc113d40c3381a33695d3ed36ae into 385064f1fa9626145d16a019324e4eca99f0e089 - [view on LGTM.com](https://lgtm.com/projects/g/fvcproductions/apprenticeships.me/rev/pr-14acff24df2326d2e16ab7d971da0b0e8cc8df23)

**new alerts:**

* 1 for Missing variable declaration

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by fvcproductions** [comment]
@benjaminmodayil I don't see the images, do we need to deploy without cache?

**Comment by fvcproductions** [comment]
Everything else looks great though!

**Comment by benjaminmodayil** [comment]
Ugh. I think I broke something with my script when I was reformatting for the codebeat bot...

It was working 😅

Looking at this now.

**Comment by fvcproductions** [comment]
I do agree the fix feels kinda hacky so we might want to consider just using Hugo with Gulp/Webpack to achieve the same thing as Parcel in the future.

**Comment by benjaminmodayil** [comment]
@fvcproductions Fixed!

Agreed. I guess we can call this a temporary fix. Launching on ProductHunt with the thumbnails really make the experience a whole lot better.

**Comment by fvcproductions** [comment]
Confirming I can see the images now - hurrah!

**Pull request merged**
